apiVersion: v1
kind: Service
metadata:
  name: testdeployment
  labels: 
    app: testdeployment
spec:
  selector:
    app: testdeployment
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 4444
